"""<migration name>

Revision ID: 1418e3e02cec
Revises: 329cfb69ad28
Create Date: 2023-04-22 15:48:23.930892

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '1418e3e02cec'
down_revision = '329cfb69ad28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('guid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sqlalchemy_utils.types.currency.CurrencyType(length=3), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_currencies_guid'), 'currencies', ['guid'], unique=False)
    op.create_table('currency_prices',
    sa.Column('guid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('currency_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_currency_prices_guid'), 'currency_prices', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_prices_guid'), table_name='currency_prices')
    op.drop_table('currency_prices')
    op.drop_index(op.f('ix_currencies_guid'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
