"""init

Revision ID: 6e89979ff539
Revises: 
Create Date: 2023-04-20 10:39:38.208822

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6e89979ff539'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('guid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_guid'), 'users', ['guid'], unique=False)
    op.create_table('transactions',
    sa.Column('guid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_transactions_guid'), 'transactions', ['guid'], unique=False)
    op.create_table('balance',
    sa.Column('guid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('transaction_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.guid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_balance_guid'), 'balance', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_guid'), table_name='balance')
    op.drop_table('balance')
    op.drop_index(op.f('ix_transactions_guid'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_users_guid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
