"""<migration name>

Revision ID: 329cfb69ad28
Revises: 63dca0650ab9
Create Date: 2023-04-22 14:50:51.965971

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '329cfb69ad28'
down_revision = '63dca0650ab9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('currency', sqlalchemy_utils.types.currency.CurrencyType(length=3), nullable=False))
    op.add_column('transactions', sa.Column('currency', sqlalchemy_utils.types.currency.CurrencyType(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'currency')
    op.drop_column('balances', 'currency')
    # ### end Alembic commands ###
