"""<migration name>

Revision ID: 75bfbee96f7c
Revises: 1418e3e02cec
Create Date: 2023-04-22 15:54:04.444619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bfbee96f7c'
down_revision = '1418e3e02cec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'currency_prices', 'currencies', ['currency_id'], ['guid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency_prices', type_='foreignkey')
    # ### end Alembic commands ###
